# Generated by Django 4.0.6 on 2022-08-06 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthday', models.DateField(verbose_name='День рождения')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['user'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='interval',
            options={'ordering': ['start_date'], 'verbose_name': 'Интервал', 'verbose_name_plural': 'Интервалы'},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lessons.interval', verbose_name='Дата занятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='event',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='event',
            name='topic',
            field=models.CharField(max_length=250, verbose_name='Тема занятия'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='end_date',
            field=models.DateTimeField(verbose_name='Конец интервала'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='start_date',
            field=models.DateTimeField(verbose_name='Начало интервала'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип пользователя'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
